name: Quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  quality:
    uses: trowaflo/github-actions/.github/workflows/quality.yml@fba3f66ab2fa1cac298095705544a7d71ed7be7f # github-actions main (pre-v3.0.0)
    with:
      enable_gitleaks: true
      enable_checkov: true
      enable_actionlint: true
      enable_markdown_lint: true
      enable_json_lint: true
      enable_kics: true
      enable_trivy: true
    permissions:
      contents: write
      pull-requests: write
      security-events: write
