name: Quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  quality:
    uses: trowaflo/github-actions/.github/workflows/quality.yml@4980c823b9d77d3cc8c69c6749e1b1884cdf1cac # PR#29 fix/deep-review-findings
    with:
      enable_gitleaks: true
      enable_checkov: true
      enable_actionlint: true
      enable_markdown_lint: true
      enable_json_lint: true
      enable_kics: true
      enable_trivy: true
    permissions:
      contents: write
      pull-requests: write
      security-events: write
