name: Quality

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  quality:
    uses: trowaflo/github-actions/.github/workflows/quality.yml@e0f15ffcf8342689bea38a3818c5899e4077dc84 # PR#26 fix/deep-review-findings
    with:
      enable_gitleaks: true
      enable_checkov: true
      enable_actionlint: true
      enable_markdown_lint: true
      enable_json_lint: true
      enable_kics: true
      enable_trivy: true
    permissions:
      contents: write
      pull-requests: write
      security-events: write
