name: Validate Renovate Config

on:
  push:
    branches: [main]
    paths: ['*.json', '*.json5']
  pull_request:
    paths: ['*.json', '*.json5']
  workflow_dispatch:

permissions: read-all

jobs:
  validate:
    uses: trowaflo/github-actions/.github/workflows/validate-renovate.yml@4980c823b9d77d3cc8c69c6749e1b1884cdf1cac # PR#29 fix/deep-review-findings
