name: Validate Renovate Config

on:
  push:
    branches: [main]
    paths: ['*.json', '*.json5']
  pull_request:
    paths: ['*.json', '*.json5']
  workflow_dispatch:

permissions: read-all

jobs:
  validate:
    uses: trowaflo/github-actions/.github/workflows/validate-renovate.yml@2b7e3d26a16bef55dcc7c5c274f97ae4fc845f08 # feat/json-lint-and-validate-renovate
