name: Validate Renovate Config

on:
  push:
    branches: [main]
    paths: ['*.json', '*.json5']
  pull_request:
    paths: ['*.json', '*.json5']
  workflow_dispatch:

permissions: read-all

jobs:
  validate:
    uses: trowaflo/github-actions/.github/workflows/validate-renovate.yml@fd881256daff836dd9595efd90f646c26a6deae4 # v2.0.0
